{% set name = "napari-trait2d" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-trait2d-{{ version }}.tar.gz
  sha256: bda41e7a1a8415411f21f3dec33b1cd0727117edf3993d166791bf648ccdfe63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dacite
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - superqt

test:
  imports:
    - napari_trait2d
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jacopoabramo/napari-trait2d
  summary: A napari plugin for TRAIT2D, a software for quantitative analysis of single particle diffusion data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jacopoabramo
    - jaimergp
